(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 60,
	color: "#FFFFFF",
	webfonts: {},
	manifest: [
		{src:"images/bg_shine.png", id:"bg_shine"},
		{src:"images/bot_gb.png", id:"bot_gb"},
		{src:"images/bot_ipa.png", id:"bot_ipa"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.bg_shine = function() {
	this.initialize(img.bg_shine);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,224,371);


(lib.bot_gb = function() {
	this.initialize(img.bot_gb);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,73,298);


(lib.bot_ipa = function() {
	this.initialize(img.bot_ipa);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,73,298);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9CSIAAkjIB7AAIAAApIhNAAIAABTIA9AAIAAAnIg9AAIAABXIBNAAIAAApg");
	this.shape.setTransform(52,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAmCmIAAgnIh3AAIAAkkIAuAAIAAD6IAyAAIAAj6IAvAAIAAD7IAUAAIAABQg");
	this.shape_1.setTransform(36.3,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAfCzIAAjNIgTBHIglCGIgvAAIAAkkIApAAIAAC4IARhAIAkh4IAzAAIAAEkgAgiiQQgLgNgBgVIAcAAQABALAFAEQAFAEAHAAQAKAAAFgEQAFgEABgLIAcAAQAAAVgMANQgMAMgZAAQgWAAgMgMg");
	this.shape_2.setTransform(18.8,-2.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAiCSIgIg1Ig3AAIgIA1IgqAAIAukjIBDAAIAvEjgAgXA1IAqAAIgTiSg");
	this.shape_3.setTransform(2.6,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgyCDQgRgUAAgjIAAiXQAAgkARgTQASgTAgAAQAiAAARATQARATAAAkIAAAdIgrAAIAAggQAAgQgHgGQgGgHgLAAQgJAAgGAHQgHAGAAAQIAACdQAAAQAHAGQAGAGAJAAQALAAAGgGQAHgGAAgQIAAgqIArAAIAAAnQAAAjgRAUQgRATgiAAQggAAgSgTg");
	this.shape_4.setTransform(-12.6,1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAiCSIgIg1Ig3AAIgIA1IgrAAIAwkjIBBAAIAvEjgAgXA1IArAAIgViSg");
	this.shape_5.setTransform(-33,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAZCSIAAh+IgyAAIAAB+IguAAIAAkjIAuAAIAAB+IAyAAIAAh+IAvAAIAAEjg");
	this.shape_6.setTransform(-49.1,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.2,-23.8,120.4,47.7);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAfCzIAAjNIgTBHIglCGIgvAAIAAkkIApAAIAAC4IARhAIAkh4IAzAAIAAEkgAgiiQQgLgNgBgVIAcAAQABALAFAEQAFAEAHAAQAKAAAFgEQAFgEABgLIAcAAQAAAVgMANQgMAMgZAAQgWAAgMgMg");
	this.shape.setTransform(49.9,-2.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag7CTIAAgqQASACAKgFQAKgFADgPIABgDIhAjhIAtAAIAaBlIAMBDIALhDIAVhlIAwAAIgxDZQgFAUgGAPQgGAPgKAJQgJAKgQAEQgLADgQAAIgNAAg");
	this.shape_1.setTransform(32.8,1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyCDQgRgUAAgjIAAiXQAAgkARgTQASgTAgAAQAiAAARATQARATAAAkIAAAdIgrAAIAAggQAAgQgHgGQgGgHgLAAQgJAAgGAHQgHAGAAAQIAACdQAAAQAHAGQAGAGAJAAQALAAAGgGQAHgGAAgQIAAgqIArAAIAAAnQAAAjgRAUQgRATgiAAQggAAgSgTg");
	this.shape_2.setTransform(16.5,1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAiCSIgIg1Ig3AAIgIA1IgrAAIAvkjIBCAAIAvEjgAgXA1IAqAAIgUiSg");
	this.shape_3.setTransform(0.2,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhSCTIAAgqIAOgBQAFgBADgDQADgDACgGQACgGAAgLIAHjcICBAAIAAEkIgvAAIAAj6IgmAAIgGCwQAAAogRARQgPASgiAAg");
	this.shape_4.setTransform(-18.1,1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAiCSIgIg1Ig3AAIgIA1IgrAAIAvkjIBDAAIAuEjgAgXA1IAqAAIgTiSg");
	this.shape_5.setTransform(-35,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag7CSIAAkjIB3AAIAAApIhJAAIAAD6g");
	this.shape_6.setTransform(-50.7,1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.6,-23.8,121.2,47.7);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ag4BvIAAgVIAIADIAJABQANgBAHgKQAGgJAEgPIg2isIAZAAIAmCGIABAAIAmiGIAZAAIg1CqQgEAQgHANQgDAMgKAIQgKAIgQAAQgJAAgIgDg");
	this.shape.setTransform(64,6.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgIB0QgGgCgGgFQgGgEgFgKIgBAAIAAARIgYAAIAAjkIAYAAIAABNIABAAQAHgLAJgGQAJgFAJAAQAVAAAMAMQAMAMAEAVQAFARAAAYQAAAYgEAVQgEAVgMANQgLAMgWABIgMgBgAgSgiQgGAGgDALQgDAKgBAKIgBAYIABAYQABANADAKQADAKAGAGQAHAHALAAQARAAAHgUQAIgSgBgjIAAgUQgBgJgEgKQgDgMgHgGQgHgHgJgBQgLABgHAGg");
	this.shape_1.setTransform(50.1,0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgNAPIAAgdIAbAAIAAAdg");
	this.shape_2.setTransform(38.7,10.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgjBWIAAipIAXAAIAAAcIABAAQAGgPAIgIQALgHAQAAIADAAIAEABIAAAXIgGAAIgFgBQgTABgIAMQgKANgBAVIAABlg");
	this.shape_3.setTransform(31.2,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgbBRQgMgIgHgUQgHgUAAghQAAgPACgQQADgPAGgNQAGgNAKgJQALgHAPgBQASAAALAJQALAIAFAPQAFAOACAQQACARgBAPIhQAAQgBAUACAOQACAPAHAHQAGAIAMAAQAMAAAGgGQAGgHACgIQACgKAAgKIAYAAQAAARgFAOQgFAOgMAIQgLAJgSgBQgQAAgNgIgAAcgNQAAgOgCgMQgCgNgGgHQgGgJgMAAQgLAAgGAJQgHAJgCAMQgCANABAMIA3AAIAAAAg");
	this.shape_4.setTransform(18.7,3.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgbBRQgMgIgHgUQgHgUAAghQAAgPACgQQADgPAGgNQAGgNAKgJQALgHAPgBQASAAALAJQALAIAFAPQAFAOACAQQACARgBAPIhQAAQgBAUACAOQACAPAHAHQAGAIAMAAQAMAAAGgGQAGgHACgIQACgKAAgKIAYAAQAAARgFAOQgFAOgMAIQgLAJgSgBQgQAAgNgIgAAcgNQAAgOgCgMQgCgNgGgHQgGgJgMAAQgLAAgGAJQgHAJgCAMQgCANABAMIA3AAIAAAAg");
	this.shape_5.setTransform(5.1,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgIB0QgGgCgGgFQgGgEgFgKIgBAAIAAARIgYAAIAAjkIAYAAIAABNIABAAQAHgLAJgGQAJgFAJAAQAVAAAMAMQAMAMAEAVQAFARAAAYQAAAYgEAVQgEAVgMANQgLAMgWABIgMgBgAgSgiQgGAGgDALQgDAKgBAKIgBAYIABAYQABANADAKQADAKAGAGQAHAHALAAQARAAAHgUQAIgSgBgjIAAgUQgBgJgEgKQgDgMgHgGQgHgHgJgBQgLABgHAGg");
	this.shape_6.setTransform(-8.9,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAKBsQgHAAgDgBQgHgCgCgGQgEgGAAgNIAAh4IgXAAIAAgVIAXAAIAAguIAXAAIAAAuIAbAAIAAAVIgbAAIAAByQgBAIACADQADADAGAAIARAAIAAAUg");
	this.shape_7.setTransform(-20.9,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgLBzIAAiVIgZAAIAAgUIAZAAIAAgPQgBgOADgKQADgLAGgEQAIgGARAAIAGAAIAGAAIAAAVIgFgBIgEAAQgJAAgEAFQgEAFAAAMIAAASIAaAAIAAAUIgaAAIAACVg");
	this.shape_8.setTransform(-29.5,0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgvBOQgLgMAAgYQAAgOAEgLQAFgJAJgGQAKgFAPgGIAMgEIAJgGIAHgCQAEgCACgGQABgGgBgGQABgPgGgGQgGgGgMAAQgOAAgGAHQgGAIABAPIgWAAQAAgaAMgMQANgNAYAAQAPABALAFQAKAGAFALQAFAKAAALIAABjQAAAGACAEQACADAFABIADAAIADgBIAAASIgFABIgFABQgIAAgFgBQgFgCgDgGQgEgEgCgMIAAAAQgFAMgKAHQgJAIgMAAQgWAAgLgLgAAAABIgPAIQgIAGgFAHQgEAHgBANQAAALAGAHQAFAHAMABQALAAAGgGQAHgEADgIQADgIgBgJIAAgoIgTAIg");
	this.shape_9.setTransform(-39.9,3.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgkBWIAAipIAYAAIAAAcIABAAQAGgPAIgIQALgHAQAAIADAAIAEABIAAAXIgGAAIgFgBQgTABgIAMQgKANgBAVIAABlg");
	this.shape_10.setTransform(-50.8,3.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgaBSQgMgIgGgMQgGgMgCgQQgCgPAAgRQAAgQACgPQADgRAGgNQAHgNALgJQAMgHAQgBQARABAMAHQALAJAGANQAGANAAAQIgXAAQAAgKgDgIQgCgJgHgGQgFgFgMAAQgMAAgIALQgHAKgCARQgDAPABARIAAAWQABALADALQADAKAGAGQAIAHAJAAQAMAAAHgHQAGgGACgKQACgKABgLIAXAAQAAARgFAPQgFAOgLAJQgLAJgUAAQgRABgMgIg");
	this.shape_11.setTransform(-63.1,3.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.3,-20.6,144.6,41.2);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFCC00","rgba(255,204,0,0)"],[0,1],0,0,0,0,0,217.7).s().p("A3vXwQp2p2AAt6QAAt5J2p2QJ2p2N5AAQN6AAJ2J2QJ2J2AAN5QAAN6p2J2Qp2J2t6AAQt5AAp2p2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-215,-215,430,430);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUBxIAAgiIAgAAIAAAigAgSA/QgCgGAAgIQAAgMADgJQACgJAFgHIAJgNQADgGAEgJQAEgIADgKQADgKAAgOQAAgMgEgFQgFgFgHAAQgIAAgEAFQgFAFAAAMIAAAZIghAAIAAgXQAAgbANgOQANgPAYAAQAZAAANAPQANAOAAAbQAAAPgDALQgDALgEAIIgLAOIgKAOQgEAHgDAIQgDAIAAALIABAMg");
	this.shape.setTransform(45.3,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBwIAAifIgZCfIgfAAIgaidIAACdIgeAAIAAjeIAwAAIAYCdIAZidIAwAAIAADeg");
	this.shape_1.setTransform(31.3,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAsBwIAAjeIAjAAIAADegAhOBwIAAjeIAjAAIAABTIAQAAQAbABALAOQANAMAAAbIAAAdQAAAbgNAOQgLAOgbABgAgrBPIAQAAQAJABAEgFQAFgEAAgMIAAgiQAAgNgFgEQgEgFgJABIgQAAg");
	this.shape_2.setTransform(13.7,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhSBwIAAjeIAkAAIAAC9IAeAAIAAi9IAhAAIAAC9IAfAAIAAi9IAiAAIAADeg");
	this.shape_3.setTransform(-4.7,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgyBwIAAjeIAyAAQAagBANAOQANAOgBAcIAAAdQABAagNANQgNAOgaAAIgQAAIAABVgAgQgCIAQAAQAHgBAFgEQAFgEgBgNIAAghQABgMgFgFQgFgFgHAAIgQAAg");
	this.shape_4.setTransform(-19.5,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBwIAAjeIBeAAIAAAfIg7AAIAAA/IAuAAIAAAeIguAAIAABBIA7AAIAAAhg");
	this.shape_5.setTransform(-31.3,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATBwIAAi/IgmAAIAAC/IgjAAIAAjeIBtAAIAADeg");
	this.shape_6.setTransform(-43.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.7,-18.6,105.4,37.3);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgzBwIAAjeIAjAAIAABTIAQAAQAaABAMAOQANAMABAbIAAAdQgBAbgNAOQgMAOgaABgAgQBPIAQAAQAHABAFgFQAEgEABgMIAAgiQgBgNgEgEQgFgFgHABIgQAAg");
	this.shape.setTransform(84.7,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAcB+IAAgdIhaAAIAAjeIAjAAIAAC9IAmAAIAAi9IAkAAIAAC+IAPAAIAAA9g");
	this.shape_1.setTransform(71.7,2.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBwIgHgpIgpAAIgFApIghAAIAkjeIAyAAIAjDegAgRApIAgAAIgPhwg");
	this.shape_2.setTransform(58,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1BwIAAjeIA1AAQAagBAMANQAMANAAAaIAAAIQAAARgFAMQgGAKgLAGQAOAFAGALQAGANAAARIAAATQAAAagOANQgNAOgbAAgAgSBPIASAAQAJAAAFgEQAFgFAAgMIAAgUQAAgPgGgHQgFgFgKAAIgQAAgAgSgUIAOAAQAIABAGgGQAFgEAAgOIAAgNQAAgMgEgFQgFgGgHAAIgRAAg");
	this.shape_3.setTransform(45.6,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAaBwIgHgpIgpAAIgFApIghAAIAkjeIAyAAIAjDegAgRApIAgAAIgPhwg");
	this.shape_4.setTransform(32.8,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQBwIAAi/IglAAIAAgfIBrAAIAAAfIglAAIAAC/g");
	this.shape_5.setTransform(21,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhSBwIAAjeIAkAAIAAC9IAeAAIAAi9IAhAAIAAC9IAfAAIAAi9IAiAAIAADeg");
	this.shape_6.setTransform(6.1,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAaBwIgHgpIgpAAIgFApIghAAIAkjeIAyAAIAjDegAgRApIAgAAIgPhwg");
	this.shape_7.setTransform(-9.6,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAVBwIgghZIgLAUIAABFIgjAAIAAjeIAjAAIAABhIAshhIAjAAIgwBjIAwB7g");
	this.shape_8.setTransform(-21.9,0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAaBwIgHgpIgpAAIgFApIghAAIAkjeIAyAAIAjDegAgRApIAgAAIgPhwg");
	this.shape_9.setTransform(-35.1,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AATBwIAAi/IgmAAIAAC/IgjAAIAAjeIBtAAIAADeg");
	this.shape_10.setTransform(-48,0.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQBwIAAjeIAhAAIAADeg");
	this.shape_11.setTransform(-62,0.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAVBwIgghZIgLAUIAABFIgjAAIAAjeIAjAAIAABhIAshhIAjAAIgwBjIAwB7g");
	this.shape_12.setTransform(-70.8,0.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AATBwIAAhbIgMAAQgKAAgGAFQgFAHAAAQIAAAjIAAALIgBAIIgBAEIgCAFIgjAAQACgHABgGIABgOIAAgjQAAgSAEgMQAFgMAOgGQgXgJAAgiIAAgSQAAgaAMgNQAMgNAaABIA1AAIAADegAgKhJQgEAFAAAMIAAAWQAAAOAGAFQAFAFAIAAIAOAAIAAhFIgRAAQgHAAgFAGg");
	this.shape_13.setTransform(-84.3,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.4,-18.6,184.9,37.3);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A52714").s().p("ABaXEIg0AAIgIAAIgDAAQgkgDgSgLQgQgCgMgJIgLgEQgbgKgUgVQgJgEgLgLIgOgLIgagaQgLgGADgJQgEgHABgHQgHgWgEguIgEgQQgHgMANgKQALgHAOgBQAJgCASABIAaAAQAOAAADAGQADAGgGAOIAAAfQAAAHAEAJIAFAOQANAcAqAlQAJACAFAKIAAAAQAFAGAMAEQALAFAFAFIAdAOQAkAPAmgXQAVgWAHgKIAJgOIAFgGQgBgFADgHIAEgMIgFgPQgIgFACgHIADgOIgIgMQgKgJgSgEIgegEQgDgBgOAAQgBACgFAAQgFAAgBAEQgFAjALAUQAIAQgIAJIgGAAQgkAAgSADQgRACgHgGQgFgFgBgTIAAgGQgDgNAAgHQgFgPADgSIAJggQACgFAFAAIAKABIACgBQACgOAOADIBpADQAegHAXAGQAsAJAiArQAiAggPA2QgBAEgEABIgBAHQAAAMgKANQgBAEgDAAIgLAPQgEAIgEABQgXAbgYAHQgWANgXACQgTAFgSAAIgKAAgAj1SzIgYgjQgHgKACgHIgGgUQgMgOASgEQANgDACAAIABACIAPgDIgCgBIAUgEQAKABAEAOQABADAHgBIAQgCQAcgJAdAAIABAEIA3gFIAEgDQAKABAUgCQAUgCAKABQAHgDAPgBQAPgBAIgDQAKgDAHAEQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgEABIATgDIgEAAQgEAAgBgDQAAgDAQgCQAQgBAMADQgCACgEABIAKgDQAGgCADAAQgCgDgHABQgJABgCgCQAFgCAIgBIAPgBQAFAAADAEQADADAAAEQgBAGAAAKIABARQAAAKgKAAQgsAPg2AIQglAHg+AEQgLAGgUgDQgUgEgcABIgxADQgLABgGAJQgGALgEAFIgDABQgEADgEAAIgEgBgAhQQrIgGgCQhCgCgpguQgHgBABgFQABgHAGAFIACAAIAAgFIgFgDQgJgFAEgDIADgGQABgFAFACQAJACAAgKQAAgDAFgBIAKgCQAFgMASgRQAFgMAOgJIAYgQIAggQQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAABABQAwgSAggJIAFgCIAFgBIALgCIAEgDQgEgDgFAAIgKAAIgVACQgPACgJgBQhfALg4gLIAAAAQgIAAgQgFIgCgBQgMAAgLgGQgMABgKgIIgSgRQgJgIAJgJIAHgKQAEgHAEgCQAHgMAEgDIAGgGQAKgMACgEQAEgHADgBQAEgCAGAGQAAgBABAAQABgBAAAAQABAAAAAAQABABAAAAQADAEABAAIADgFQADgCAFAEQAIAGAQAEIAaAFIBYgBQAiAAAtgEIBQgIIAIgBQAEAAAEACIBYADQANAAACADQAIAAABACQAEADAAAJQACA+ADAfQABALgEAGQgEAGgLAEIiRAwQhaAeg2ARIgFABIgEACIgEAFIELAIQAOAAAJAGIABABQAIAIAEAPIAIAYQAAADgCACQgCADgDgBIgMAAQgGAAgEgDQgmgHguARQgNAFgTABIghADIgyABQgvAAgtgEgAhILCQgHgBgQgFIgNgEQgJgBgNgEIgWgGQgIAAgIgEIgPgIIgBgBQgDABgEgCIgIgDQgKgEgCgCIgDgDIgEAAIAJALQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgDAEgEgCQgcgPgPgbQgFgFgEgKQgEgFgIgVQgRgtABgkIgBgtQAAgbAFgTIABgDQADgLAJgJIARgOIANgNIAIgIQAGgDAHACQAFgGADACQACABAFAHIAAAFQAAAEAGgCQAOgCgDASQgSBRAmBOIABAHQADAFALAJQAJAIADAHQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABQAGgCAFAEIAKAGQAjARAKADQALACAEAJQAVAEAdgDQAbgEBdgBQAtAAAygKQAXgLAMgSQAGgMgGgQQgLgTgMgeIgjg0IgdgaIgUgIQhAgNg5AQIgMAEQgIADgDAHQAFAvAOAvQACAIgCACQgCADgGAAIggAAQgUgBgNACQgJACgBgJQgMgrAFg1IABgEIAAgBIAAgEQAAgLADgEQACgOAQgTIAIgRQAFgKAGgFQAIgJAQgDIAGgCQABgHgEAAIgGACQgzgCgagEIgJgDQgIgBgCgCQgHABgEgEQgTAAgQgOQgIgHgSgWIgHgGQgFAIgEgDIgGgIQgEgEABgKQgDgPAAgYIgDgnIgGg2QgDgfADgYQgBgGACgDIAIgUQAIgJAQgBIABAAQADgDAKABQAMgCAPABQAEAFgDAIQgFAJAAADQACBUgIBaQAPAJAlAFQAcAEBEACQAHABACgDQACgDgBgGQgEgfADg4IAEgwQACgdgBgTQAAgIAFAAIArgBQAHAAAAADIAEAVQADAMgCAIQgFAdgBAZIgCBpQAMACASAAIAeAAQAQACAhABQAIABADgEQACgCgCgJQgEglAFgWQgGgFgBgBQgCgEAGgEQABgGAIAAIAIgDQALgGAAgOIAAhdQgBgKALgBIAjgEIAEgBQABAAAAAAQABABAAAAQAAAAABABQAAAAABABQABACgDAEQgGAHgBAKQAAAFABAMQACARABAfIABAwIAJB9IABAOQAAAIgHAEIgQAAQgHADgJAAIgQgBIgeADQgIAAAAAGQAdAKAUAWQAlAeAPAvIANAVQAGAMABALQANAjAAAtQgBAUgGA9QACAJgFAIIgKAUQgHAKgLACQAAgCAFgEIAEgKIgEACIgBABQgWASgSADQhNARiDgFQgHAAgIABIgRADIgHAAQgOAAgegDgAinBKIADAGIAAgHgAjRAIQgFgBgGgEIgLgFQgNgRgEgaIgCguQABgGABgwQABghALgUIAFgMIAMgOQAIADAFgHIAHgKQAFAFAFAAQAEABAHgEIAGgEQADgCAEAAQAigCAnALIAJAGQABAEAGAEIAIAGQAEAFADgCIADgFIAJAOQAAAGADAGIAGARIAAACIAAAHQAAADADACQABACgBAHQgCAGAFACQADAEgBACQgGACABAJQAAAAAAABQAAAAABABQAAAAABAAQABAAABAAQAOAAAFgCQAJgEACgMIAIgNQAKgGAPgPQARgRAJgGQAHgDgCgHQAIAAAEgJIAAgCQAQgHAZgSIARgMQAJgHAEgIIAHgJQAIAAABgGIgBgLQAFAAAHgGQANgEAYgNIAFgCQADgCABgCQAPgCAEAEQAFAEgBAPQgDAnABANQACAdgZAFQgLAAgHAJQgRABgNAKQgDABgEAFIgGAJIgHgCQgEgBACAIQgaAQgcAYQgQAJgIAQIgGAHQgLAEgLAKIgSATQgEAEAHAAIADADQAEgEAFAEIBlACQA6ABAqgEQAIgBACAIIAEAkQABAJgEACQgGADgFgGIgGAAIgDgBQgPAAgIACIgJgBQgFAAgEADIgFAAQgLgCgGAFIgLABQgHAAgFgBQgDAAgEABIgHADQgrAChGAEIhuAHQgpACggAAIgpgBgAitikIgHAIQgEAFAAAFQgQAZACAoQAAAKAKAAIBpAAQADAAAEgCQADgCgBgDQgCgIAEgNQAFgOgCgHQABgGgFgGIgHgJQgFgUgbgGQgQgDgNAAQgSAAgOAGgAiJmTQgJgGgOgDIgagDQgbgDgGgDQgJAAgBgKIgEg6IgDgnQgDgSAOgaQAGgOAHgHQAJgOALgDIABgBQABgDAEgCIAHgDQAdgOAhAKQAJACAFAEQAeAMASARQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAEACQAAAAABAAQABAAAAAAQAAgBAAAAQABAAAAgBIAAgEQABgZAGgRIADgGQAAgFAFgFQAGgKANgIIACgDQABAAAAgBQAAAAAAAAQAAgBgBAAQAAgBgBAAIgggDIgEAAIgEgCIgwgFIgmACIgJAGQgFAEgDAEIgCABQgEABgGgGQgFgFAAgFQAEgygGguQgBgKACgIQAEhRAAgWIAAgVQgCgGAFABQAHADAKAAIARAAQAGAAABACQACABAAAGIADAHQACAEAEABQACAAAAAHQAGBPgRA7IgBACIAAADQgCAIABABQABABAJAAIBXgDQAGAAAAgGQAGg4ADhCIAAgMQABgIADgFIAGgTQAAgKAFAHIACgBIAEgBIANAAQAHAAAFgCQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAABIABACQACAFAAAHIgBAMQAEAKgBANIgDAXIgEA1IgDApQAAAHABABQACACAGAAIAaABQARACAJgBIAEABQAUACA7gGQACgDgBgEIgBgPIAAgOQgIgPACgZIADgqQABgIACgCIABgCIADgCIACgPQAAgEAEgFQADgGAAgDQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAIAAIAIAAIAYgDQAFAAAAADIABAJQADAGgBAEQgDAQADAZQAAAJAGgBQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAFALAAALQgCApACAbQABALgBAUIAAAfQAAAFgFAAIghAEIgUAAQgIAAgGACQAPAIADAKQAGAGABAGQAUAgAGASIABADIALAVQABABADAHQACACAAAEQAAAhgCAaIAAAZIgBAuQAAAJgJgBIgWgCQgGACgKgBQgLgCgFABIhDAEQgZAEgPgBIgDABIheAFIgFgBQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABIABABIAAABQACACgFAAQgQACgfgBQgUgBgEABQgHAEgJAAQgJAAgKgDgAh1ngQAAAAABgBQAAAAAAAAQABgBAAgBQAAAAAAgBQAAgBAAAAQAAAAABAAQAAAAABgBQAAAAABAAIAGAAQAHACAEgEQAEgEAFgBIALAAQAQgCAMACQABAAABAAQABAAAAAAQABAAAAAAQABgBAAAAQABgBgBgEQgCgLAAgEQgHgWgIgQQgEgJgPgFIgagIIgMAAIgXAEQgVALgEADIgFAEIgSAjQAAAEgDAJQgCAHABAFQAAAHAHAAIA5ADQAFAAABABIABAAIADABgAB7pYIgHADQgDACgIABIgBABQgTAJgLAAQgDACgHABIgTAHIgEABQgGACgBAEQABANgDAPIAAABQAFAHABAJIABARIgBARQAAAGAGAAICCgGQAKgJABgOQACgbgDgdIgEgHIgHgKIgKgKQgJgHgPgHQgKAHgGABgAg4u6QgQgCgGgDQgGgBgBgEIgKgHQgCgCgEAAIgGgDQgHABgIgDIgMgHIgWgKIgfgIQgEgBgBgEIABgGIgDgEQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQgHgNAIgJQABgCgBgGIgGhJQgBgkAEhHIABgEQAAgCAEAAQASACAiAAQAKAAAAAJIAAAHQABACAEABQABAAABABQAAAAABAAQAAABABAAQAAABAAAAIAAAFQADAFgBAFQAFANgDASQgDAWgDApQgDAqgDAUIAAACIA7ABQAAAAABAAQAAAAABgBQAAAAAAAAQAAAAAAAAIgCgCQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAEgDQABAAAAAAQABgBAAAAQABAAAAABQABAAABAAQAAAAABAAQABAAAAABQAAAAABAAQAAAAAAABIADABQAQACAOADIAZADIACgIQgBgQADgXIAFgmIABggIAAgOQgBgVABgRQAAgHACgBQABgBAHACIApAEIAGgBQAEABAAAEIAIAoQAAAIgBAJQgIA6gHAcIgFAXQgEAJAJgBIAEABIA6AFQAUADA2gGIAJgCQACgCgBgFQgLhvgJgwQgDgSABgHQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAbgQQAHgEAUgHQAEgDADAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABABQADABABAEIACACQAMALAAAYIgGDuIgBAFIgGABIgVAAQhEAMhHAEIgsABQgyAAg4gFgAhTz3QgRAAgFgDIgBgBQgCABgDAAIgGgBQgJAAgjAEQgHABgCgCQgLABgFgCQgGgCgBgCQgPgJgPgXIgLgMQgFgGAAgOQgEgRAHgOIAAAAQACgOAEgGQAMgiAUgUQADgEAHgCQAFgEANgHIAOgIQALgFAPABQAKAAAJACIACABIAMADQAIABAEACIAmALQAIADADADIAEADQADABAGAHQALAIAFARQADAFABALQAAAGADgDQADgDAEgBQAHgHAMgGIATgJIALgFQANgJATgFQAEgDAJgCQAIgBAEgCQACgDAFAAIABAAQAHgCAbgDIAagBQAXgEAUACQAIAAAagDQASgBAJACIABAAIABAAQAJAAACADIAAAaQABAHgGgBQgOAFgOAAQgFAAgFABIgrAPIgBABIgpANIg0ASQgFAEgIACIg1AXIgEAEQgBABAAAAQgBAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQABAAAAAAQABAAABAAIAFAAQAyADBkgIIAcgEQAKgEAXgDQAGgDAVAAQABAAABAAQAAABABAAQAAABAAAAQABABAAABQABATgDAJIAAADQACAFgDACQgCAAgCAEQgCADgCAAQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAIADABIgnARIgIABQgDACgeAEQg9AIhKgFQgJgBgGgEIgBABQgGAAgCgFQgfgDgPABIgQAEQgCAFgFABIgIABIgHAAIgEABIgFAAIgbABIgPAAgAiB2KQgQALgKAFIgEAEQgKAYgBALQgCANADANQAAAFAGAAQATAAADABIAkACQAWABANgBQAGgKABgTIAAgZQgDgEgCgLQgDgLgDgFIgDgFIgDgDQgKgDgKAAQgPAAgOAHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.8,-147.6,59.7,295.4);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#349054").s().p("AjGXbQgJgKgOgTIgXgfQgNgSgOgcIgXgxQgFgOAFgHQAFgFADAHIAGALQABABABABQAAABABAAQAAAAABAAQAAAAABgBQAAAAABgBQAAAAAAAAQAAgBAAAAQAAAAAAAAIgCgDQgEgMgBgIQgBgGAFgEQABAAABgBQAAAAABAAQAAAAABABQAAAAAAABIADAEIAGAMIACgBQAIgKAGANIAUAnQADAFADAAQAdgBA7AGIBjAIQAvADAyAAQA0AAAigDIALgDQAEgBAFACQAGADADAAIACAHQACANAHAAQAFgBAAAHQABAEgFABIgGACQgDABABAGQAAAGADAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIAAAEQABAEgFAAQgFABAAAHIAAAYQAAAKgEACQgEADgIgBIgKgDQgHgEgEAAQgFgBAAgFQAAgGgDgCIgGAAIklgBQAAACADADQACAFgDADQgEAFgEgEIgFgFQgDgEgEACIAQAZIACADQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAIgGAFQgDABgGgCQgGgCgDAFIgBAAQgCAAgFgHgAA1WnIAYAAIAAgBIgYAAgAgqWIQAAABAAAAQAAABAAAAQAAAAABABQAAAAAAAAIBDADQAJACAMgBIAUgBQgIgEgFACQgWgGgbAAQgNAAgiACgAAmV1QAFADAHAAIAMgCQgEgCgHgBIgYAAQgEgCgIABIgPAAQAFAEAKgBgAjAUeIgpgvQgEgEgBgIQAAgHABgGIABgBQgDgJAEgEIAJgGIAcgaQARgRALgIQAngdAtgUQAHgBACgEQhAgdgsgfQgMgIgbgLIgGgBIgHABQgGAAgCgIQgEgOAAgQQABgCgEgEIgKgQQgGgIABgEQAAgFAIgFIADgCQAGgCABgDICRAaQAMAAAVADIAgACQANABATAGQAYAHAHABQAzAKAcACQA0AEAgAGIARACQAJABAGAEQAGADAAADQAAAFgFADQgMAIgQAPIgbAZIgbAbQgGAEgJAEIgPADQgOAFgkACQgTAAgUANQgQAJgDACQg6AcgnAlQAAABABAAQAAAAABAAQAAAAABABQABAAAAAAIAGAAQArABBTAGQANABAWgCIAjgCIAdgDQARgBALABQAPABABATIgBAMQABAHAHABQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQgBAEgDACIgHABQgCAAAAAFIgCADQAAABAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAEABgBAIQAAACgFACIgEABQgNgBgoAEIgdACQgSABgLACQgHACgOAAIgVAAQhAAEghAEQgiAFgRABIgaABIgLAAIgFABQgMAAgJgKgADFOxQgRgRgPgHQgGgDgHgPQgEgGgGACQhzAQhFASQgXAGgYgBIilgeIAEgDIAXgLQAHgCgEgHIgLgZIgCgFQAAgBgBAAQAAgBAAgBQAAAAAAgBQABAAAAgBQAEgGAFACIAFABIgIgRQgDgGABgDQACgEADgBIAJgFQAGgDAEACQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAIAAgEIANg8QAHglAXgiQALgRAYgMIAQgJQAPgJAWgFIAmgHQAYgGAZAEQAWADAPAIQAeARAkAfIAWAQQA2AlAKBPIAHAlQAEASAKACQADABAAADIAAAFQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAAAQgGABADAIQAEAJgEAQQgBAFgFAEQgGADgIgBIAHARQABAHgCACQgEADgCAAIgCgBgAh/L7QgIAFgHAJIgLASQgCAEACAGIABAIQgBAEACABIAFABIAugBIBkgIQA8gEAqAFIgsgfQgagUgRgKQgKgHgHgBQgUgEgSAAQgxAAgmAZgAijJ+IgIgCIgHgFQgJgJgJgTIgPgfIgQgcQgEgKAAgGQgBgIAFgIQAKgOgEgSIgDgTIgBgFQAAgBABAAQAAgBAAAAQAAgBABAAQABAAAAAAQAEgCADAGQAEANALARIgEgiQgBgHADgBQABAAAAgBQABAAAAABQABAAAAAAQABAAAAAAIACAFIAEAJQACAFAFgBQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAABIAJATQACAGAGAAID+gBQAPAAARgLQgSgHgkgQQgigRgSgGQgBABgBAGQAAAEgEAAQgDABgDgFIgCgHQgBgEgFgCIhIgYQgpgQgdgQQgwgagignQgJgKgMgSIgUgfIgOgWIgIgOQgEgJABgFQABgFAIgGQADgDAAgDQgBgNANgEQBLgWAlgEQAlgEAjAHQAYAEAvAEQAMABAVABQAWAAALACQAZACAQAAIApAAQAOABAMACQAJABAQgHQAKgEAEAHQABAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAEgBQAJgBAAAGQABAIADADIAJAFQAGAEAAACQABAEgGAFIgcAfQgRATgLAOQgEAHgDgCQgFgFABgGQABgEgDgBQgFgCgCABQgDACgFABIgvAPQgOADgkABQgEAAgBABIgDAHQgCAOAAAVIAAAkIAAAYQAAAIAGADQAmARBOAbIAbALQARAHAMACIAUADQAFABACAGQABAFgCAFIgHAJQgHAEABAIQAAAFgBACQgCABgEgBQgNgDAAAOQAAABAAABQAAAAAAABQAAAAAAABQAAAAgBAAQgGgCgDAHQgEAJgDABQgCAAAAAIIAAAbQgBAMgKgBIgbgDQgjgFgbAFQgmAHgrgHQgJgBgRACIgbADQgRAAgfAFIgXABQgPAAgIABQgEABAAAGIACAZIAAAFQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAQgHAAgCgEIgFgHIACAaQACAJgEAAIgDgBgAgYIcQAEABAMAAIAHAAQgBgCgEAAIgFgBIgFAAQgQgEgIACIgOAAQAEAEAGgBgAAREVQACAHgBAJQgCACACAHQACAGgDADQgDAKAAAQIAAAbQAAABAAAAQAAABABABQAAAAABAAQAAABABAAQACAAAAgFIAAgrIABgGQABgOgBghQgDADAAAHgAh/EKQgYAEgSAFQACADAHADQANAJAqAWQAyAbAjALQAEACABgGQACgUgCgpQgBgOgCgCQgCgCgLgBIgwgCIgJAAQgWAAgRACgAjnAJQgNgCgNgIQAAgBgBgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgCAFgCQgIgEACgFIAAgCIgCgCQgEgBgCgIQgBgGgCgDIAAgEIADgCQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgHgMADgLQACgHAAgQQADgQAJghQAEgNAAgJIAIgaQAFgUAWgHIASgFIAFgBQADAAACgBIgfgeIgCgCQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQADgFAEgBIADABQgBgHgHgGQgEgFABgDQAAgBgDgFIgUg2QgFgQALgPQAEgEADAAQAEgBADgEQAEgIAGgBIACgBQASgLAdgDIAqgKIAUgEQAMgCAHAAQAMAAARgFIAlgFQAEgBACgEQACgEADgBQAHgFACAHQAAABAAAAQAAABAAAAQABAAAAAAQAAABABAAIAAgDQACgGADgDQgNAAgWAFIgEABIgaADIgbADQgWACgLADIgrACQgKAAgEAEIgJADIgLABQgHAAgEgDQgDgCgEgBQgPgDgHgUQgEgKgQgcIgMgbQgCgFgDAAQAAgEAEAAIAAAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQABAAAAAAQAEgJAJAAQAMAAAVgCQAXgDAKAAQAYAAAxgCQAKAAAEADQABAAAAABQAAAAABAAQABAAAAAAQABAAABAAQAzAAAwgBIA5gDQAEgBAAgEQgDgNgDgYIgDghIAAgMQgCgJAFgDQACgCAEABIAFACIAIADQADgKgBgIQAAgKAEgbQACgQAAgFQAAgIAIACIAPAGQAEACAAgFIAAgBQABgGABgBQACgBAFACQAPAFAfAGQAGABgBAFQgBAGADALQABADADAAIAFABQAGACgDAEIAGAaQACAOAAALIABBTIABAEQACALAAARQAAAMgNAHQAAAAAAAAQgBAAAAABQAAAAAAABQAAAAAAABQABAAAAABQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQgDgBgCADIgFADIAAABQABABAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQADgEAFAAIAJACQAXADAMgCQAEgBAAAEQAAAFAFAAIAFgBIADAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABQADAFgFAEQAEgBACAEIAEAFIACACQAFAAAAAEQACAGgDAFQgGAKgLAJQgaATguASQgmAPg4ARIgYAFQgBAAgBABQAAAAgBABQAAAAAAABQAAAAAAABIAAA4QABAHAGABQAVADAbACQAsADAuACQAFABAAAEQAAAFgFAAQgLAAgDACIgDABIADAAIAQABIAGAAQAEABAAAEIADAAIAKABQAFAAgBAGQAAAEgFAAQgHAAgZAEQAAAAAAAAQgBABAAAAQAAAAABAAQAAABAAAAIAXACQAGABgBAGQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAIgUACIgUACIgnAAIgeABIgeACIgXACQgQAAgIACIgXABIgiACQgVADgKgCIAAABIASAEQAnAIAZAPQAPAHAHAMIACACQAQAJAFAWQACAPgCAkIgCAIQgDAFAGAAIAjACQAWABAOgBIAjgCIAjAAIAFAAQAEABAAAEIACABIACAAQABAAABAAQABAAAAABQABAAAAABQAAAAAAABIABADQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEABIAMABQACAAAEACQADACACAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIgBACIgGAFIAEAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgIAGQgBAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQABAAAAABQAAAAAAAAQABAAAAABQAAAAABAAIAAgBQAFgBAAADQABAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgCACIgCABIgEACIACAAIAFABQAAAAABABQAAABAAAAQAAABgBAAQAAAAgBABIgRAIQgKACgIgBQgSAAgeACIgwACIhHAAQgNgBgkAEQgYABgkgCIgXABIgRABIhVABIgdAAgAAsgVIgIABIgJABIAdAAQgEgDgEACQAAAAAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgCAAgABcgYQgRAAgLAEIAlgDIAEgCIgHAAIgGABgABogtIg7AGQgFAAgDAEIABABQA0gCAUgEIAIgBIAHgCIACABQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQgEgCgBACQgEgCgIAAIgIAAgAhcimQgcACgTAOQgEACgDAGQgCAIgDAQQgDARgIAiQgBAFAFAAIBNAFQAEAAABgDQABgFAEACQABAAABAAQAAAAABAAQABAAAAAAQAAAAABgBIAMgOQALgNgCgSIAAgHQgEgXgEgFQgOgWgYAAIgBAAgAgZlPQgxAIgYAGIhDAQIAFALIADACIAPAAIB9AEQAHAAAAgCQABgBgBgHIgCgKQgBgQgBgDIgBgFQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAAAAAIgCgBIgHACgABZnVIgOABQgIABgOADIgWAEIgRAFIABADQACAHAHgBIAbgHIA3gPIALgCIAEgBIADAAIADgBQgBgBgFABIgDABQgFgBgDACIgFABIgCAAIgIgBIgGABgACArpQhTgEg2ABIhuACIhRABQgJAAgMgFQgNgEgGAAQgEAAgGgDQgFgCgCAEIgDAEQgCACgDAAQgDAAgCgCIAAgCQgHgCgCgLIAAgEIgDhjIAAgIQgBgFgDgCQAAAAgBAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAABgBIACgBQAFgGgFgFQgEgEAEgCQAEgEgDgJQgDgKAIgGQANgJAZgVQAEgDAUgHQAFgCAAgFQACgEACgCQADgBAEADIAGAEQAFADABAFQAAAFAEgBQAGgCACAHQAFANgBAJQAAAFABALIABAQIAAALQgBAJAAARIAAAbQAAABAAAAQAAABABAAQAAABABAAQAAAAABAAQAZAAAxACQAEAAAAgDIAIgoIAAgPQABgYAEgHQABgDAAgJIAEgZQAAgGACgBQACgBAGABIAAAFQADgEgBgDIAEgYQABgEADABIAEAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIACAAQAGACABACIAAAJIgBAEQAAAAAAAAQAAABAAAAQAAAAAAAAQABAAAAAAIABgCQABgEgBgGQADgGABgBQABAAAAAAQAAAAABAAQABAAAAAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQgBAEAFgBQAGgBAAAHIAAAHIAAAEQAAABAAAAQABAAAAABQAAAAABAAQABABAAAAQACAAAAAFQABAIgDAaQgBAWAABGQAAAGAGABQBBAEAZAAQAFAAACgFQAFgQACgaIADgpIAHgeIABgCQAEgBACgEIACgIIACgNQAAgEACgBIAFAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIAAADIAAAFIABACQADgCAGABQABAAAAAAQABABAAAAQABAAAAAAQAAAAAAAAIAAgDIACgFQAAAAAAgBQABAAAAgBQABAAAAAAQABAAABAAQAEAAAAAFIABAGQAHgCACACQADABAAAIIAAADIAAAFQAAAAAAAAQABABAAAAQABAAABAAQAAAAABAAQAEAAAAAGIgBAaQABAQgBAPQgBAhgBAJIgBAJQAAABABAAQAAAAAAAAQABAAAAABQAAAAABAAIAEAAQAHAAACAEQADAFgGAAIgCABIABAAIADABQAHACAPAAIAFABQADABAAAFQAAAAAAAAQAAAAgBABQAAAAgBAAQgBAAgBABIgcAIIAAAAIACAAIALAAQAGAAAEACQADACABADQABAEgCADQAAAAgBABQAAABgBAAQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAABgBAAQAAABAAAAQgEADgFAJQgGAJgEADQAGAEgEACIgGADIACABQABAAABAAQABAAAAAAQAAABABAAQAAABAAABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQgSAHgcAAIgNAAgABhwuIgGgLIAAAJQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIAAgDIgGgPQgBgDgEgEQgFgEgFABQgMAEgYABIgZAEQgbADgJgBQgJACgEgCIgEgBIgVglQgBgCABgEIACg2QABghgBgVIgBgrQgCgZgDgSQgCgKgHgUQgDgUgBgQQgCglADgZIAAgOQAAgFABgCQACAAAFADIAAgIQAAgIAGACQABAAAAAAQABABAAAAQAAgBABAAQAAAAAAAAQACgHAHgCQABAAAAAAQABAAAAAAQABAAAAAAQABABABAAIAAADQAAAOABADIADgCQAEgEADABQADAAAAAHIAAAOQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAIADABQAAAAABAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAQABABAAAAIAAAMQgCAsAEA9IAJB4IAEBGQAAAHAHgBIASAAIAUgCQATgEAZgBQABAAAAgBQABAAAAAAQABgBAAgBQAAAAAAgBQAFgXgBgXIgBg2IgCgeIgEgEQgFgCAEgFQAEgGgBgHIgHhUIgFg3QgBgEADgHQACgDABgHIADgKIACgEQADAAAEgEQAEgDAEgBQAFgBACgDQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAQACADAHAAQAigBAyAIQAXADALgBQADAAAPAEQAMADAWAHQAGABgCAHQgBAGABACQABAAAAAAQAAAAAAAAQABAAgBAAQAAABAAAAIgBALQAAAIgCAEQgEAIgGABIgBABQgFAJgKgFIgBgBQgMgGgQACQgJABgSAFIgsAKQgSAEgOgFQgFgCABAGIAGBZQAAAEAFgBIAfgEQARgCANADQAaAEAMAEIARAGQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgDACQAGACAAADQAAADgGAFIADACIACABQACADAAACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCAAQgHABgCADQgBABgEAAQgDAAgCACIAIAAQAFAAAHABQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAgBAAIgFABQAAAAgBAAQAAAAAAABQAAAAgBABQAAABAAABIgBABQgGgBgJAEQgLAEgEAAIgwAHQgRADgQgBQAAAAgBAAQgBABAAAAQAAAAAAABQgBABAAABQACAXAABAQAAAGAGAAIAuADQAJgBAUACQAmgBAbgDQAHgBAFAFQACADAFAAQADgCABAFIAAACIgCABIgGAEIgDACQAAAAAAAAQAAABAAAAQAAABAAAAQAAABABABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgLAJQgGAIgSAAIgQAAQgjgCgRABIgPABQgJACgFAFQgCACgIABIgaAEQgFACgDgDQgBgBAAAAQgBAAAAAAQgBgBAAABQgBAAgBAAQgCACgBADIABADQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABIgBAAQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBgAhC0RIAAALQAAAHACACIgBgVgAkTw6QAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgFQAAgKAGgZIAfiPIAEgQQAEgLACgWQAEgQADgFQABgDABgHIAKg8IAFgWQADgOAAgJQAAgMAOgKQABgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAIADAAQABAAAAAAQABAAABAAQAAAAAAAAQABAAAAABIAAADIgCAMIABAAQAIgIgBgFQAAgCAEgDIAegZQADACgBADIgBAGQADAAADgDQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABgBAAQgBADACAGIAAAKQgDAMACAQIAEAcQACAPAIAhQAHAfACARQAIA5AKA1IAFAkQABAFACAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgDABAAAEIACA3QAAAEgGAIQgBABAAAAQAAAAgBAAQAAAAgBAAQAAAAgBgBIgBABIAAABIgBABIAAAFQAAABAAAAQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAgBQgCgJgGgEQgCgCgDgLIgGgfQgBgFgFgBQgZgGgNgBIgHgCQgOgHgSAFQgFABgJgEIgEgBQgCAAgBAFIgEAdIgIAlQgBACgGADQgEACgBAEQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgDgFAAIgKgBQgEgCgCAFIgBADIgBABIgBAAgAiKyPQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQgCgBgFAAIgFgBIgIgBQADACAFAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIADABgAi30eIgVBNIAHAJQAbABAoAIQAFABgBgGQgEgSgJgeQgEgPAIgIQABgBAAgFIgNgoIgOgzQgJAcgNAyg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.8,-150.6,59.6,301.3);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],68.3,0,144.2,0).s().p("EgWhA+fMAAAh89MAtDAAAMAAAB89g");
	this.shape.setTransform(-106.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250.5,-400,288.5,800);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7EDDA9").s().p("AgrBeIAAi7IAeAAIAABHIANAAQAWAAALAMQAKAKABAXIAAAZQgBAWgKAMQgLAMgWAAgAgNBDIANAAQAGAAAEgEQAEgDAAgLIAAgcQAAgLgEgDQgEgEgGAAIgNAAg");
	this.shape.setTransform(29.3,0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7EDDA9").s().p("Ag0BeIAAgbIAJgBQADAAACgCQACgCABgEIACgKIAEiNIBSAAIAAC7IgeAAIAAigIgYAAIgDBwQgBAagKALQgLALgWAAg");
	this.shape_1.setTransform(17.6,0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7EDDA9").s().p("AggBUQgLgNAAgWIAAgXIAcAAIAAAZQAAAKAFAEQAEAEAGAAQAGAAAEgEQAEgEAAgKIAAgpIgZAAIAAgaIAZAAIAAghQAAgLgEgEQgEgEgGAAQgGAAgEAEQgFAEAAALIAAASIgbAAIAAgQQAAgYALgMQALgMAUAAQAVAAAMAMQALAMAAAYIAABgQAAAWgLANQgMAMgVAAQgUAAgMgMg");
	this.shape_2.setTransform(7.1,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-16,36.2,32.1);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7EDDA9").s().p("AgNBeIAAi7IAbAAIAAC7g");
	this.shape.setTransform(80.4,0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7EDDA9").s().p("AASBeIgbhMIgJASIAAA6IgdAAIAAi7IAdAAIAABTIAlhTIAeAAIgqBUIAqBng");
	this.shape_1.setTransform(73.1,0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7EDDA9").s().p("AggBUQgLgNAAgWIAAhgQAAgYALgMQALgMAVAAQAVAAALAMQAMAMAAAYIAAASIgcAAIAAgUQAAgLgFgEQgEgEgHAAQgFAAgEAEQgEAEAAALIAABkQAAAKAEAEQAEAEAFAAQAHAAAEgEQAFgEAAgKIAAgbIAcAAIAAAZQAAAWgMANQgLAMgVAAQgVAAgLgMg");
	this.shape_2.setTransform(62.4,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#7EDDA9").s().p("AAUBzIAAiDIgNAsIgWBXIgfAAIAAi7IAbAAIAAB1IAKgpIAXhMIAhAAIAAC7gAgVhcQgIgJAAgNIASAAQABAHADADQADACAEAAQAGAAAEgCQADgDAAgHIASAAQABANgJAJQgHAIgQAAQgOAAgHgIg");
	this.shape_3.setTransform(51.7,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#7EDDA9").s().p("AAlBeIAAi7IAeAAIAAC7gAhCBeIAAi7IAeAAIAABHIAOAAQAWAAAJAMQALAKAAAXIAAAZQAAAWgLAMQgJAMgWAAgAgkBDIAOAAQAHAAAEgEQADgDAAgLIAAgcQAAgLgDgDQgEgEgHAAIgOAAg");
	this.shape_4.setTransform(38.5,0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#7EDDA9").s().p("AAfBrIAAgaIg+AAIAAAaIgcAAIAAg0IALAAQAEgFABgGIACgOIAHiIIBRAAIAAChIANAAIAAA0gAgLAeQgBALgCAFQgCAFgEAEIAlAAIAAiGIgXAAg");
	this.shape_5.setTransform(24.4,1.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7EDDA9").s().p("AAQBeIAAhRIggAAIAABRIgdAAIAAi7IAdAAIAABRIAgAAIAAhRIAeAAIAAC7g");
	this.shape_6.setTransform(12.5,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7EDDA9").s().p("AgNBeIAAi7IAbAAIAAC7g");
	this.shape_7.setTransform(4.6,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-16,84.8,32.1);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FE8A3D").s().p("EgnDAXbMAAAgu1MBOHAAAMAAAAu1g");
	this.shape.setTransform(0,149);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250,-1,500,300);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7EDDA9").s().p("EgnDAXcMAAAgu2MBOHAAAMAAAAu2g");
	this.shape.setTransform(0,-150);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250,-300,500,300);


(lib.Symbol7copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAuBzIAAjlIAkAAIAADlgAhRBzIAAjlIAlAAIAABXIAQAAQAcAAAMAPQANAMAAAcIAAAeQAAAcgNAPQgMAOgcAAgAgsBSIAQAAQAJAAAFgEQAFgFgBgNIAAgjQABgMgFgFQgFgEgJAAIgQAAg");
	this.shape.setTransform(103.2,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUBzIAAhjIgoAAIAABjIgkAAIAAjlIAkAAIAABjIAoAAIAAhjIAlAAIAADlg");
	this.shape_1.setTransform(87,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBnQgNgPAAgcIAAgaIAhAAIAAAcQABANAFAEQAFAGAIAAQAHAAAFgGQAFgFAAgPIAAgSQAAgQgFgIQgGgGgKAAIgJAAIAAgfIAKAAQAIAAAHgGQAFgFAAgOIAAgMQAAgQgFgFQgFgFgHAAQgIAAgFAEQgFAGgBAMIAAATIghAAIAAgRQAAgdANgOQAOgPAZAAQAaABANAPQAPAPAAAcIAAAFQAAAlgaALQAOAFAGALQAGANAAARIAAATQAAAcgPAPQgNAOgaAAQgZAAgOgOg");
	this.shape_2.setTransform(73.9,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwCJIAAjlIBhAAIAAAhIg9AAIAAA+IAxAAIAAAhIgxAAIAABEIA9AAIAAAhgAAJhoIAAggIAfAAIAAAggAgohoIAAggIAgAAIAAAgg");
	this.shape_3.setTransform(61.8,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLAiIgFhDIAhAAIgFBDg");
	this.shape_4.setTransform(53,-7.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BzIAAjlIA1AAQAbAAANAOQANAPAAAcIAAAeQAAAbgNAOQgNAOgbAAIgQAAIAABXgAgQgCIAQAAQAHAAAGgGQAEgEAAgNIAAgiQAAgMgEgFQgGgFgHAAIgQAAg");
	this.shape_5.setTransform(44.7,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AguBzIAAggQAPABAHgEQAIgEACgMIABgCIgziwIAkAAIAVBPIAJA0IAIg0IARhPIAmAAIgnCqQgDAQgFALQgFAMgIAHQgHAIgMADQgJACgNAAIgKAAg");
	this.shape_6.setTransform(31.7,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgnBnQgOgPAAgcIAAh2QAAgcAOgPQAOgPAZgBQAaABAOAPQAOAPAAAcIAAAWIgjAAIAAgZQAAgMgFgGQgFgEgIAAQgHAAgFAEQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAghIAjAAIAAAfQAAAcgOAPQgOAOgaAAQgZAAgOgOg");
	this.shape_7.setTransform(19,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgRBzIAAjlIAjAAIAADlg");
	this.shape_8.setTransform(5.1,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,114.6,38.3);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRBzIAAjlIAjAAIAADlg");
	this.shape.setTransform(86.6,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWBzIghhcIgLAVIAABHIglAAIAAjlIAlAAIAABlIAthlIAlAAIgzBnIAzB+g");
	this.shape_1.setTransform(77.5,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAmCCIAAgeIhMAAIAAAeIgjAAIAAg/IAOAAQAFgGACgHIACgRIAIinIBkAAIAADFIAQAAIAAA/gAgOAlQgBAMgCAIQgDAGgEAEIAtAAIAAijIgdAAg");
	this.shape_2.setTransform(62.5,2.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBnQgPgPAAgcIAAh2QAAgcAPgPQAOgPAZgBQAaABAOAPQAPAPAAAcIAAB2QAAAcgPAPQgOAOgaAAQgZAAgOgOgAgMhPQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAh7QAAgMgFgGQgFgEgIAAQgHAAgFAEg");
	this.shape_3.setTransform(48.4,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhABzIAAghIAKgBQAEAAADgDQADgCABgFIACgNIAFisIBlAAIAADlIglAAIAAjEIgeAAIgDCJQgBAggNAOQgMANgbAAg");
	this.shape_4.setTransform(34.3,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBzIgHgqIgrAAIgFAqIgiAAIAljlIA0AAIAkDlgAgRApIAhAAIgQhyg");
	this.shape_5.setTransform(21.1,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnBnQgOgPAAgcIAAh2QAAgcAOgPQAOgPAZgBQAaABAOAPQAOAPAAAcIAAAWIgjAAIAAgZQAAgMgFgGQgFgEgIAAQgHAAgFAEQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAghIAjAAIAAAfQAAAcgOAPQgOAOgaAAQgZAAgOgOg");
	this.shape_6.setTransform(8.4,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,91.5,38.3);


(lib.Symbol6copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgfAJQgLgJAAgTIAZAAQABAKAFAEQAEADAHAAQAIAAAEgDQAFgEABgKIAZAAQAAATgLAJQgMALgUAAQgUAAgLgLg");
	this.shape.setTransform(83,-14);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAtBzIAAjlIAlAAIAADlgAhRBzIAAjlIAkAAIAABXIARAAQAcAAAMAPQANAMAAAcIAAAeQAAAcgNAPQgMAOgcAAgAgtBSIARAAQAJAAAFgEQAEgFAAgNIAAgjQAAgMgEgFQgFgEgJAAIgRAAg");
	this.shape_1.setTransform(112.7,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AATBzIAAhjIgmAAIAABjIglAAIAAjlIAlAAIAABjIAmAAIAAhjIAmAAIAADlg");
	this.shape_2.setTransform(96.5,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgtBzIAAggQAOABAHgEQAIgEACgMIABgCIgyiwIAkAAIAUBPIAIA0IAJg0IARhPIAlAAIgmCqQgEAQgEALQgFAMgIAHQgHAIgMADQgJACgNAAIgJAAg");
	this.shape_3.setTransform(83.2,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBnQgPgPAAgcIAAh2QAAgcAPgPQAOgPAZgBQAaABAOAPQAPAPAAAcIAAB2QAAAcgPAPQgOAOgaAAQgZAAgOgOgAgMhPQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAh7QAAgMgFgGQgFgEgIAAQgHAAgFAEg");
	this.shape_4.setTransform(70.3,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRBzIAAjEIgmAAIAAghIBvAAIAAAhIgmAAIAADEg");
	this.shape_5.setTransform(58.3,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATBzIAAhjIgmAAIAABjIglAAIAAjlIAlAAIAABjIAmAAIAAhjIAmAAIAADlg");
	this.shape_6.setTransform(45.8,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AguBzIAAggQAPABAHgEQAIgEADgMIAAgCIgziwIAkAAIAVBPIAJA0IAIg0IARhPIAmAAIgnCqQgDAQgFALQgFAMgIAHQgHAIgMADQgJACgNAAIgKAAg");
	this.shape_7.setTransform(32.5,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag1BzIAAjlIA1AAQAbAAANAOQANAPAAAcIAAAeQAAAbgNAOQgNAOgbAAIgQAAIAABXgAgQgCIAQAAQAHAAAGgGQAEgEAAgNIAAgiQAAgMgEgFQgGgFgHAAIgQAAg");
	this.shape_8.setTransform(20.4,0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AguBzIAAjlIBdAAIAAAhIg5AAIAADEg");
	this.shape_9.setTransform(8.1,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,124.1,38.3);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguBzIAAggQAPABAHgEQAIgEACgMIABgCIgziwIAkAAIAVBPIAJA0IAIg0IARhPIAmAAIgnCqQgDAQgFALQgFAMgIAHQgHAIgMADQgJACgNAAIgKAAg");
	this.shape.setTransform(77.1,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBzIgbhcIgeBcIgiAAIAoh1IgmhwIAmAAIAZBVIAchVIAiAAIgmBwIApB1g");
	this.shape_1.setTransform(63.7,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAuBzIAAjlIAkAAIAADlgAhRBzIAAjlIAlAAIAABXIAQAAQAcAAALAPQAOAMAAAcIAAAeQAAAcgOAPQgLAOgcAAgAgsBSIAQAAQAJAAAFgEQAFgFgBgNIAAgjQABgMgFgFQgFgEgJAAIgQAAg");
	this.shape_2.setTransform(47.4,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1BzIAAjlIA1AAQAbAAANAOQANAPAAAcIAAAeQAAAbgNAOQgNAOgbAAIgQAAIAABXgAgQgCIAQAAQAHAAAGgGQAEgEAAgNIAAgiQAAgMgEgFQgGgFgHAAIgQAAg");
	this.shape_3.setTransform(32.5,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAWBzIghhcIgLAVIAABHIglAAIAAjlIAlAAIAABlIAthlIAlAAIgzBnIAzB+g");
	this.shape_4.setTransform(19.9,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRBzIAAjlIAjAAIAADlg");
	this.shape_5.setTransform(5.1,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,85.6,38.3);


(lib.Symbol5copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAWBzIghhcIgLAVIAABHIglAAIAAjlIAlAAIAABlIAthlIAlAAIgzBnIAzB+g");
	this.shape.setTransform(52.2,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBzIgHgqIgrAAIgGAqIghAAIAljlIA0AAIAkDlgAgRApIAhAAIgQhyg");
	this.shape_1.setTransform(38.5,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AApBzIAAijIgZCjIggAAIgbiiIAACiIggAAIAAjlIAzAAIAYCiIAZiiIAzAAIAADlg");
	this.shape_2.setTransform(23.3,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBnQgOgPAAgcIAAh2QAAgcAOgPQAOgPAZgBQAaABAOAPQAOAPAAAcIAAAWIgjAAIAAgZQAAgMgFgGQgFgEgIAAQgHAAgFAEQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAghIAjAAIAAAfQAAAcgOAPQgOAOgaAAQgZAAgOgOg");
	this.shape_3.setTransform(8.4,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,60.3,38.3);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRBzIAAjlIAjAAIAADlg");
	this.shape.setTransform(117,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWBzIghhcIgLAVIAABHIglAAIAAjlIAlAAIAABlIAthlIAlAAIgzBnIAzB+g");
	this.shape_1.setTransform(108,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBzIAAjlIBdAAIAAAhIg5AAIAADEg");
	this.shape_2.setTransform(95.1,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwCJIAAjlIBhAAIAAAhIg9AAIAAA+IAxAAIAAAhIgxAAIAABEIA9AAIAAAhgAAJhoIAAggIAfAAIAAAggAgohoIAAggIAgAAIAAAgg");
	this.shape_3.setTransform(83.5,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhABzIAAghIALgBQAEAAACgDQACgCACgFIABgNIAHisIBkAAIAADlIglAAIAAjEIgdAAIgFCJQgBAggMAOQgNANgbAAg");
	this.shape_4.setTransform(69.7,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAWBzIghhcIgLAVIAABHIglAAIAAjlIAlAAIAABlIAthlIAlAAIgzBnIAzB+g");
	this.shape_5.setTransform(52.2,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAbBzIgHgqIgrAAIgGAqIghAAIAljlIA0AAIAkDlgAgRApIAhAAIgQhyg");
	this.shape_6.setTransform(38.5,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AApBzIAAijIgZCjIggAAIgbiiIAACiIggAAIAAjlIAzAAIAYCiIAZiiIAzAAIAADlg");
	this.shape_7.setTransform(23.3,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgnBnQgOgPAAgcIAAh2QAAgcAOgPQAOgPAZgBQAaABAOAPQAOAPAAAcIAAAWIgjAAIAAgZQAAgMgFgGQgFgEgIAAQgHAAgFAEQgFAGAAAMIAAB7QAAANAFAEQAFAGAHAAQAIAAAFgGQAFgEAAgNIAAghIAjAAIAAAfQAAAcgOAPQgOAOgaAAQgZAAgOgOg");
	this.shape_8.setTransform(8.4,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-19.2,122,38.3);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FE8A3D").s().p("AAjDRIgCgHIgCgJIgCgOIAAgVIAAhCQAAgdgKgMQgKgNgVAAIgXAAIAACrIhCAAIAAmhIBkAAQAxAAAXAXQAYAYAAAxIAAAhQAABBgsATQAZAJAKAXQAJAYAAAhIAABBIABAbQABAMAFALgAgjgTIAaAAQAQAAALgKQAKgJAAgaIAAgpQAAgXgIgKQgIgLgPAAIggAAg");
	this.shape.setTransform(82,1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FE8A3D").s().p("AhZDRIAAmhICyAAIAAA7IhwAAIAAB1IBZAAIAAA6IhZAAIAAB8IBwAAIAAA7g");
	this.shape_1.setTransform(59.1,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FE8A3D").s().p("AhYDRIAAmhICxAAIAAA7IhwAAIAAB1IBZAAIAAA6IhZAAIAAB8IBwAAIAAA7g");
	this.shape_2.setTransform(37.4,1.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FE8A3D").s().p("AhkDRIAAmhIBjAAQAxAAAYAXQAXAYAAAxIAAAPQAAAhgKAUQgLAWgWAKQAbAKALAVQAMAXAAAiIAAAiQAAAwgaAaQgZAZgyAAgAgjCWIAkAAQARgBAIgIQAKgKgBgXIAAglQABgdgLgKQgKgMgUAAIgeAAgAgjglIAaAAQARAAAKgKQALgJAAgaIAAgXQAAgXgIgKQgJgLgOAAIghAAg");
	this.shape_3.setTransform(14.6,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-33.2,95.3,66.5);


(lib.Symbol3copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7EDDA9").s().p("ABrHOIgZioIixAAIgZCoIiEAAICTubIDTAAICTObgAhMCoICKAAIhEnRg");
	this.shape.setTransform(100.2,27.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7EDDA9").s().p("AjWHOIAAubIDWAAQBsAAA1A7QA2A6AABwIAAB4QAABwg2A4Qg1A6hsAAIhFAAIAAFcgAhFgPIBFAAQAgAAATgTQASgTAAgyIAAiKQAAgygSgTQgTgSggAAIhFAAg");
	this.shape_1.setTransform(50.2,27.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7EDDA9").s().p("AhHHOIAAubICPAAIAAObg");
	this.shape_2.setTransform(11.2,27.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.3,-46.7,132.2,141.4);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FE8A3D").s().p("AAjDRIgCgHIgCgJIgCgOIAAgVIAAhCQAAgdgKgMQgKgNgVAAIgXAAIAACrIhCAAIAAmhIBkAAQAxAAAXAXQAYAYAAAxIAAAhQAABBgsATQAZAJAKAXQAJAYAAAhIAABBIABAbQACAMAEALgAgjgTIAaAAQAQAAALgKQAKgJAAgaIAAgpQAAgXgIgKQgIgLgPAAIggAAg");
	this.shape.setTransform(118.5,1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FE8A3D").s().p("AhZDRIAAmhICyAAIAAA7IhwAAIAAB1IBZAAIAAA6IhZAAIAAB8IBwAAIAAA7g");
	this.shape_1.setTransform(95.5,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FE8A3D").s().p("AhIC7QgZgbAAgzIAAjZQAAgzAZgbQAZgbAvAAQAwAAAZAbQAZAbAAAzIAAApIg/AAIAAgtQABgXgKgJQgJgJgPAAQgPAAgIAJQgKAJAAAXIAADhQAAAXAKAJQAIAJAPAAQAPAAAJgJQAKgJgBgXIAAhNIgeAAIAAg6IBdAAIAACDQAAAzgZAbQgZAbgwAAQgvAAgZgbg");
	this.shape_2.setTransform(72.9,1.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FE8A3D").s().p("AAkDRIhQktIAAEtIg7AAIAAmhIBTAAIBBD5IAAj5IA7AAIAAGhg");
	this.shape_3.setTransform(48.8,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FE8A3D").s().p("AgfDRIAAmhIA/AAIAAGhg");
	this.shape_4.setTransform(30.7,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FE8A3D").s().p("AhIC7QgZgbAAgzIAAjZQAAgzAZgbQAZgbAvAAQAwAAAZAbQAZAbAAAzIAAApIg/AAIAAgtQAAgXgJgJQgJgJgQAAQgOAAgIAJQgKAJAAAXIAADhQAAAXAKAJQAIAJAOAAQAQAAAJgJQAJgJAAgXIAAhNIgdAAIAAg6IBcAAIAACDQAAAzgZAbQgZAbgwAAQgvAAgZgbg");
	this.shape_5.setTransform(13.7,1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-33.2,131.7,66.5);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FE8A3D").s().p("AAWBeIgGgiIgiAAIgGAiIgbAAIAfi7IApAAIAeC7gAgPAiIAcAAIgNheg");
	this.shape.setTransform(34,0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FE8A3D").s().p("AgsBeIAAi7IAsAAQAWAAAKALQAKAKAAAXIAAAGQAAAPgEAJQgFAJgKAGQAMAEAFAIQAFAKAAAQIAAAPQAAAWgLALQgLAMgXAAgAgPBDIAPAAQAIAAAEgEQAEgEAAgKIAAgRQAAgNgFgFQgEgFgIAAIgOAAgAgPgQIAMAAQAGAAAFgEQAFgFAAgLIAAgKQAAgLgEgFQgEgEgFAAIgPAAg");
	this.shape_1.setTransform(23.6,0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FE8A3D").s().p("AgNBeIAAi7IAbAAIAAC7g");
	this.shape_2.setTransform(15.7,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FE8A3D").s().p("AAQBeIAAigIggAAIAACgIgdAAIAAi7IBbAAIAAC7g");
	this.shape_3.setTransform(7.8,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-16,41.3,32.1);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FE8A3D").s().p("AgnBeIAAi7IBPAAIAAAbIgxAAIAAA1IAmAAIAAAZIgmAAIAAA3IAxAAIAAAbg");
	this.shape.setTransform(73.2,0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FE8A3D").s().p("AAVBeIgEgiIgjAAIgGAiIgbAAIAei7IAqAAIAfC7gAgPAiIAbAAIgMheg");
	this.shape_1.setTransform(62.9,0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FE8A3D").s().p("AAQBeIAAhRIggAAIAABRIgdAAIAAi7IAdAAIAABRIAgAAIAAhRIAeAAIAAC7g");
	this.shape_2.setTransform(52,0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FE8A3D").s().p("AgrBeIAAi7IArAAQAVAAAMAMQALAMgBAXIAAAZQABAVgLALQgMAMgVAAIgNAAIAABHgAgNgCIANAAQAGAAAEgEQAEgDAAgLIAAgcQAAgLgEgDQgEgEgGAAIgNAAg");
	this.shape_3.setTransform(42,0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FE8A3D").s().p("AgNBeIAAi7IAbAAIAAC7g");
	this.shape_4.setTransform(34.3,0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FE8A3D").s().p("AgtBeIAAi7IBSAAIAAAbIg0AAIAAAwIAPAAQAXAAALAMQALAKAAAXIAAAVQAAAWgLAMQgLAMgXAAgAgPBDIAPAAQAIAAADgEQAFgDAAgLIAAgYQAAgKgFgEQgDgDgIgBIgPAAg");
	this.shape_5.setTransform(26.7,0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FE8A3D").s().p("AAiBeIAAiFIgVCFIgaAAIgWiDIAACDIgaAAIAAi7IAqAAIATCEIAUiEIAqAAIAAC7g");
	this.shape_6.setTransform(14.1,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FE8A3D").s().p("AgNBeIAAi7IAbAAIAAC7g");
	this.shape_7.setTransform(4.6,0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-16,79.8,32.1);


(lib.ira = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.bot_ipa();
	this.instance.setTransform(-36,-149);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36,-149,73,298);


(lib.gb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bot_gb();
	this.instance.setTransform(-36,-149);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36,-149,73,298);


(lib.blk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AyufPMAAAg+dMAldAAAMAAAA+dg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.bg_shine_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bg_shine();
	this.instance.setTransform(-112,-185);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-112,-185,224,371);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.t2 = new lib.Symbol20();
	this.t2.setTransform(0,14.2);

	this.t1 = new lib.Symbol19();
	this.t1.setTransform(0,-14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.4,-32.8,184.9,65.6);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// sh2
	this.sh2 = new lib.Symbol21();
	this.sh2.setTransform(0,0,1.5,1.5);
	this.sh2.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.sh2).wait(1));

	// sh
	this.sh = new lib.Symbol21();
	this.sh.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.sh).wait(1));

	// Layer 5
	this.instance = new lib.Symbol16();
	this.instance.setTransform(114,1.3,1,1,180);

	this.instance_1 = new lib.Symbol16();
	this.instance_1.setTransform(-113.9,1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Layer 2
	this.gb = new lib.gb();
	this.gb.setTransform(40,4.5);

	this.ira = new lib.ira();
	this.ira.setTransform(-40,4.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.ira},{t:this.gb}]}).wait(1));

	// Layer 5
	this.n2 = new lib.Symbol18();
	this.n2.setTransform(106.4,5);

	this.timeline.addTween(cjs.Tween.get(this.n2).wait(1));

	// Layer 5
	this.n1 = new lib.Symbol17();
	this.n1.setTransform(-102.4,3.7);

	this.timeline.addTween(cjs.Tween.get(this.n1).wait(1));

	// Layer 1
	this.bg1 = new lib.bg_shine_1();
	this.bg1.setTransform(-40,-0.5);

	this.bg2 = new lib.bg_shine_1();
	this.bg2.setTransform(40,-0.5,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.bg2},{t:this.bg1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364.4,-398.7,728.9,800);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.c2 = new lib.Symbol11();

	this.c1 = new lib.Symbol10();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.c1},{t:this.c2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250,-300,500,599);


(lib.Symbol9copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.t2 = new lib.Symbol24();
	this.t2.setTransform(0,-46.6);

	this.t1 = new lib.Symbol23();
	this.t1.setTransform(0,-85.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2}]}).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AyufPMAAAg+dMAldAAAMAAAA+dgAtXArQheBeAACFQAACEBeBdQBeBfCEAAITrAAQCEAABdhfQBfhdAAiEQAAiFhfheQhdhciEAAIzrAAQiEAAheBcg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 3
	this.site = new lib.Symbol22();
	this.site.setTransform(0,24.5);

	this.timeline.addTween(cjs.Tween.get(this.site).wait(1));

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AvmXcMAAAgu3IfNAAMAAAAu3g");

	// mc
	this.mc = new lib.Symbol12();
	this.mc.setTransform(0,27,0.997,0.997,-11);

	this.mc.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AyufPMAAAg+dMAldAAAMAAAA+dgAnAJVIHLAAIAACXICrAAIAAk0IhMAAIAAvBIixAAIAAO+IjIAAIAAu+IixAAgAETJVICvAAIAAxeIivAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AvmXcMAAAgu3IfNAAMAAAAu3g");

	// mc
	this.mc = new lib.Symbol12();
	this.mc.setTransform(3,0,0.997,0.997,-51.2);

	this.mc.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.ira_t1 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.t7 = new lib.Symbol4();
	this.t7.setTransform(406.4,-588.3);

	this.t6 = new lib.Symbol3copy();
	this.t6.setTransform(-23.6,1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t6},{t:this.t7}]}).wait(1));

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArsnoIAAmRIXZAAIAAGRg");
	mask.setTransform(49.4,-89);

	// t3
	this.t3 = new lib.Symbol5copy();
	this.t3.setTransform(-23.6,-158.2);

	this.t3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.t3).wait(1));

	// Layer 8 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("Arsk0IAAmRIXZAAIAAGRg");
	mask_1.setTransform(49.4,-71);

	// t4
	this.t4 = new lib.Symbol6copy();
	this.t4.setTransform(-23.6,-122.8);

	this.t4.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.t4).wait(1));

	// Layer 9 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("ArsiFIAAmRIXZAAIAAGRg");
	mask_2.setTransform(49.4,-53.5);

	// t5
	this.t5 = new lib.Symbol7copy();
	this.t5.setTransform(-23.6,-87.5);

	this.t5.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.t5).wait(1));

	// Layer 2
	this.t2 = new lib.Symbol14();
	this.t2.setTransform(60.8,102);

	this.t1 = new lib.Symbol13();
	this.t1.setTransform(-23.6,102);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.9,-621.5,528.6,739.6);


(lib.gb_t1 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.t7 = new lib.Symbol4();
	this.t7.setTransform(-23.6,51.7);

	this.t6 = new lib.Symbol3();
	this.t6.setTransform(-23.6,1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t6},{t:this.t7}]}).wait(1));

	// Layer 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArsnoIAAmRIXZAAIAAGRg");
	mask.setTransform(49.4,-89);

	// t3
	this.t3 = new lib.Symbol5();
	this.t3.setTransform(-23.6,-158.2);

	this.t3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.t3).wait(1));

	// Layer 8 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("Arsk0IAAmRIXZAAIAAGRg");
	mask_1.setTransform(49.4,-71);

	// t4
	this.t4 = new lib.Symbol6();
	this.t4.setTransform(-23.6,-122.8);

	this.t4.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.t4).wait(1));

	// Layer 9 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("ArsiFIAAmRIXZAAIAAGRg");
	mask_2.setTransform(49.4,-53.5);

	// t5
	this.t5 = new lib.Symbol7();
	this.t5.setTransform(-23.6,-87.5);

	this.t5.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.t5).wait(1));

	// Layer 2
	this.t2 = new lib.Symbol2();
	this.t2.setTransform(55.8,102);

	this.t1 = new lib.Symbol1();
	this.t1.setTransform(-23.6,102);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.t1},{t:this.t2}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.6,-177.4,131.7,295.5);


(lib.content = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		var count = 1;
		var repeat = 2000;
		var time1 = 0;
		var time2 = time1+3;
		var time3 = time2+4;
		var time4 = time3+5;
		
		var tl = new TimelineLite();
		tl.fromTo(this.blk, 0.5, {alpha:1}, {alpha:0, ease:Power0.easeNone})
		  .staggerFrom([this.pack.ira, this.pack.n1], 0.7, {x:"-=900", ease:Power0.easeNone}, 0.1, time1)
		  .staggerFrom([this.pack.gb, this.pack.n2], 0.7, {x:"+=900", ease:Power0.easeNone}, 0.1, time1)
		  .staggerFrom([this.pack.bg1, this.pack.bg2], 0.9, {alpha:0, ease:Power0.easeNone}, 0.0, time1+0.5)
		  .from(this.pack.sh, 0.1, {alpha:0, ease:Power0.easeNone}, time1+0.6)
		  .from(this.pack.sh2, 0.1, {alpha:0, ease:Power0.easeNone}, time1+0.6)
		  //shake
		  .to(this.pack, 0.1, {x:"+=10", rotation:"-=0", ease:Power0.easeNone}, time1+0.7)
		  .to(this.pack, 0.2, {x:"-=10", rotation:"+=0", ease:Elastic.easeOut}, time1+0.8)
		  
		  .staggerFrom([this.t2.t1, this.t2.t2], 0.5, {y:"+=100", scaleX:0, scaleY:0, ease:Expo.easeOut}, 0.05, time1+0.7)
		  .to(this.pack.sh, 0.4, {alpha:0, ease:Power0.easeNone}, time1+0.7)
		  .to(this.pack.sh2, 0.9, {alpha:0, ease:Power0.easeNone}, time1+0.7)
		  
		  //gb
		  .to(this.blk, 0.3, {alpha:1, ease:Power0.easeNone}, time2)
		  .staggerTo([this.pack, this.t2], 0.01, {x:900, ease:Expo.easeOut}, 0.0, time2+0.3)
		  .to(this.blk, 0.3, {alpha:0, ease:Power0.easeNone}, time2+0.31)
		  
		  .from(this.gb, 1.5, {x:"+=300", ease:Expo.easeOut}, time2+0.31)
		  .from(this.bg1, 1.0, {alpha:0, ease:Power0.easeNone}, time2+0.8)
		  
		  .staggerFrom([this.gb_t1.t1, this.gb_t1.t2], 1.0, {x:"+=300", ease:Expo.easeOut}, 0.05, time2+1.0)
		  .staggerFrom([this.gb_t1.t3, this.gb_t1.t4, this.gb_t1.t5], 1.0, {y:"+=50", ease:Expo.easeOut}, 0.10, time2+1.1)
		  .staggerFrom([this.gb_t1.t6, this.gb_t1.t7], 1.3, {x:"+=300", ease:Expo.easeOut}, 0.05, time2+1.2)
		  
		  //OR start
		  .to(this.blk, 0.3, {alpha:1, ease:Power0.easeNone}, time3)
		  .to(this.bg1, 0.3, {alpha:0, ease:Power0.easeNone}, time3)
		  .staggerTo([this.gb, this.gb_t1], 0.02, {x:900, ease:Expo.easeOut}, 0.0, time3+0.30)
		  .to(this.blk, 0.01, {alpha:0, ease:Power0.easeNone}, time3+0.4)
		  .from(this.ili, 0.01, {x:"+=1300", ease:Expo.easeOut}, time3+0.4)
		  .from(this.ili.mc, 1.0, {rotation:"-=90", ease:Expo.easeOut}, time3+0.5)
		  .from(this.ili.mc.c1, 1.2, {x:"+=500", ease:Power0.easeNone}, time3+0.0)
		  .from(this.ili.mc.c2, 1.2, {x:"-=500", ease:Power0.easeNone}, time3+0.0)
		  
		  //OR end
		  .to(this.ili.mc.c1, 1.2, {x:"-=500", ease:Power0.easeNone}, time3+1.5)
		  .to(this.ili.mc.c2, 1.2, {x:"+=500", ease:Power0.easeNone}, time3+1.5)
		  .to(this.ili.mc, 1.0, {rotation:"+=90", ease:Expo.easeIn}, time3+1.5)
		  .to(this.ili, 0.01, {x:"+=1300", ease:Expo.easeOut}, time3+2.5)
		  
		  //ira
		  .from(this.ira, 1.5, {x:"+=300", ease:Expo.easeOut}, time3+2.3)
		  .to(this.bg1, 1.0, {alpha:1, ease:Power0.easeNone}, time3+2.3)
		  
		  .staggerFrom([this.ira_t1.t1, this.ira_t1.t2], 1.0, {x:"+=300", ease:Expo.easeOut}, 0.05, time3+2.70)
		  .staggerFrom([this.ira_t1.t3, this.ira_t1.t4, this.ira_t1.t5], 1.0, {y:"+=50", ease:Expo.easeOut}, 0.10, time3+2.70)
		  .staggerFrom([this.ira_t1.t6, this.ira_t1.t7], 1.3, {x:"+=300", ease:Expo.easeOut}, 0.05, time3+2.80)
		  
		  //end
		  .to(this.blk, 0.3, {alpha:1, ease:Power0.easeNone}, time4)
		  .staggerTo([this.ira, this.ira_t1, this.bg1], 0.01, {x:900, ease:Expo.easeOut}, 0.0, time4+0.30)
		  .to(this.blk, 0.3, {alpha:0, ease:Power0.easeNone}, time4+0.31)
		  
		  .from(this.btn, 0.01, {x:"+=1300", ease:Expo.easeOut}, time4+0.4)
		  .from(this.btn.mc, 1.0, {rotation:"-=90", ease:Expo.easeOut}, time4+0.5)
		  .from(this.btn.mc.c1, 1.2, {x:"+=500", ease:Power0.easeNone}, time4+0.0)
		  .from(this.btn.mc.c2, 1.2, {x:"-=500", ease:Power0.easeNone}, time4+0.0)
		  .staggerFrom([this.btn.t1, this.btn.t2], 1.0, {y:"+=100", scaleX:0, scaleY:0, ease:Expo.easeOut}, 0.1, time4+0.20)
		  .from(this.btn.site, 1.0, {alpha:0, scaleX:2, scaleY:2, ease:Expo.easeOut}, time4+0.20)
		  
		  
		  .call(replay)
		  .to(this.blk, 0.6, {alpha:1, ease:Power0.easeNone, onComplete:restart}, 18)
		  ;
		
		function replay() {
		  if (count == repeat){
		      tl.pause();
		  } else {
		  if (count != repeat) {
			  count++;
			  tl.play();
		  }
		  }
		}
		
		function restart() {
			tl.play(0);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// warn
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#999999").s().p("AAFCLQgIAAAAgSIAAh0IgSAAIAACGIgKAAIAAkVIAKAAIAACHIASAAIAAh2QAAgRALAAIAKAAQAOAAAAARIAADyQAAASgJAAgAAFh5IAADuQgBANAHgBIAFAAQAGABABgNIAAjuQAAgIgFAAIgKAAQgDAAAAAIg");
	this.shape.setTransform(103.6,180.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#999999").s().p("AgQCaIAAgJIAFAAQAGAAAAgIIgVkEIAJAAIARDfIARjfIAKAAIgYEFQgCAQgGAAgAgNiLQgGgGAAgIIAKAAQAAAEADADQADADADAAQADAAADgDQADgDAAgEIALAAQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape_1.setTransform(93,178.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("AgHCLQgKAAAAgSIAAjyQAAgRANAAIAIAAQAOAAAAARIAADyQAAASgKAAgAgHh5IAADuQAAANAFgBIAEAAQAHABAAgNIAAjuQgBgIgEAAIgIAAQgDAAAAAIg");
	this.shape_2.setTransform(83.8,180.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB3QAAALgEACQgFADgGAAIgLAAIAACGgAgIgDIALAAQAGAAAAgJIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_3.setTransform(75.4,180.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_4.setTransform(66.2,180.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#999999").s().p("AARCYIAAgaIghAAIAAAaIgJAAIAAgjIAFAAQAGAAAAgNIAAj/IAjAAIAAEMIAFAAIAAAjgAgFBtIAAAIIARAAIAAkCIgRAAg");
	this.shape_5.setTransform(56.1,181.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAANAGgBIAFAAQAGABAAgNIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGAAAAgJIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABuQAAALgGAAIADABQADABAAAJIAABuQAAASgJAAg");
	this.shape_6.setTransform(47,180.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#999999").s().p("AgQCLIAAgKIAFAAQAGABAAgJIgVkDIAJAAIARDeIARjeIAKAAIgYEFQgCAQgGAAg");
	this.shape_7.setTransform(27.1,180.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#999999").s().p("AASCLIAAiXIgOCXIgIAAIgMiXIAACXIgKAAIAAkVIAKAAIAQDgIASjgIAJAAIAAEVg");
	this.shape_8.setTransform(17,180.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_9.setTransform(6.9,180.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#999999").s().p("AgfCLIAAkVIAJAAIAAELIATAAIAAkLIAHAAIAAELIATAAIAAkLIAJAAIAAEVg");
	this.shape_10.setTransform(-3.7,180.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_11.setTransform(-14.4,180.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB3QAAALgGAAIADABQADABAAAJIAAB3QAAAJgEAAgAgICBIAOAAQADAAAAgGIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGAAAAgJIAAhxQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_12.setTransform(-23.6,180.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#999999").s().p("AgRCLIAAkVIAJAAIAACHIALAAQAGAAAFADQAEADAAAKIAAB1QAAAJgGAAgAgICBIAPAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAAAAAgBIAAhvQAAgKgGAAIgLAAg");
	this.shape_13.setTransform(-42.6,180.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#999999").s().p("AANCYIAAgaIgjAAIAAkVIAJAAIAAEMIARAAIAAkMIAJAAIAAEMIAKAAIAAAjg");
	this.shape_14.setTransform(-51.4,181.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#999999").s().p("AgDCLIAAkVIAHAAIAAEVg");
	this.shape_15.setTransform(-58.8,180.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAANAGgBIAFAAQAGABAAgNIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGAAAAgJIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABuQAAALgGAAIADABQADABAAAJIAABuQAAASgJAAg");
	this.shape_16.setTransform(-65.8,180.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#999999").s().p("AARCYIAAgaIghAAIAAAaIgJAAIAAgjIAFAAQAGAAAAgNIAAj/IAjAAIAAEMIAFAAIAAAjgAgFBtIAAAIIARAAIAAkCIgRAAg");
	this.shape_17.setTransform(-74.9,181.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAjyQAAgRAOAAIAIAAQANAAAAARIAADyQAAASgKAAgAgIh5IAADuQAAANAHgBIADAAQAGABAAgNIAAjuQAAgIgDAAIgIAAQgFAAAAAIg");
	this.shape_18.setTransform(-84,180.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#999999").s().p("AAJCLIgRiGIAACGIgJAAIAAkVIAJAAIAACHIARiHIAJAAIgSCKIASCLg");
	this.shape_19.setTransform(-92.4,180.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#999999").s().p("AgfCLIAAkVIAJAAIAAELIATAAIAAkLIAHAAIAAELIATAAIAAkLIAJAAIAAEVg");
	this.shape_20.setTransform(-102.1,180.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_21.setTransform(103.9,147.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgGAAIADAAQADACAAAIIAAB4QAAAJgEAAgAgICBIAOAAQADABAAgHIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_22.setTransform(94.7,147.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#999999").s().p("AgDCLIAAkVIAHAAIAAEVg");
	this.shape_23.setTransform(87.7,147.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#999999").s().p("AAJCLIAAkMIgRAAIAAEMIgJAAIAAkVIAjAAIAAEVg");
	this.shape_24.setTransform(80.8,147.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_25.setTransform(62.1,147.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_26.setTransform(54.1,147.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_27.setTransform(45.7,147.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_28.setTransform(36.5,147.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgGAAIADAAQADACAAAIIAAB4QAAAJgEAAgAgICBIAOAAQADABAAgHIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_29.setTransform(27.2,147.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#999999").s().p("AAXCLIAAkVIAJAAIAAEVgAgfCLIAAkVIAJAAIAACHIANAAQAGABADACQAEADAAAKIAAB1QAAAJgEAAgAgWCBIARAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAgBAAAAIAAhvQAAgKgGAAIgNAAg");
	this.shape_30.setTransform(17.5,147.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#999999").s().p("AAXCLIgTiGIAACGIgHAAIAAiGIgTCGIgJAAIAUiLIgUiKIAJAAIATCHIAAiHIAHAAIAACHIATiHIAJAAIgUCKIAUCLg");
	this.shape_31.setTransform(6.4,147.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#999999").s().p("AgQCaIAAgJIAFAAQAGAAAAgIIgVkEIAJAAIARDfIARjfIAKAAIgYEFQgCAQgGAAgAgNiLQgGgGAAgIIAKAAQAAAEADADQADADADAAQADAAADgDQADgDAAgEIALAAQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape_32.setTransform(-4.2,146);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_33.setTransform(-23.8,147.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_34.setTransform(-32.7,147.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_35.setTransform(-42,147.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgEABQgFAEgGAAIgLAAIAACGgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_36.setTransform(-50.3,147.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_37.setTransform(-58.4,147.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#999999").s().p("AARCLIAAiXIgMCXIgIAAIgOiXIAACXIgJAAIAAkVIAJAAIARDhIARjhIAKAAIAAEVg");
	this.shape_38.setTransform(-67.3,147.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAAMAGAAIAFAAQAGAAAAgMIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGABAAgKIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABvQAAAKgGAAIADAAQADACAAAIIAABvQAAASgJAAg");
	this.shape_39.setTransform(-76.5,147.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_40.setTransform(-85.8,147.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgEABQgFAEgGAAIgLAAIAACGgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_41.setTransform(-95,147.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#999999").s().p("AAJCLIAAkMIgRAAIAAEMIgJAAIAAkVIAjAAIAAEVg");
	this.shape_42.setTransform(-103.4,147.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#999999").s().p("AAFCLQgIAAAAgSIAAh0IgSAAIAACGIgKAAIAAkVIAKAAIAACHIASAAIAAh2QAAgRALAAIALAAQANAAAAARIAADyQAAASgKAAgAAFh5IAADuQAAANAGgBIAFAAQAHABgBgNIAAjuQAAgIgDAAIgLAAQgDAAAAAIg");
	this.shape_43.setTransform(103,180.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#999999").s().p("AgQCaIAAgJIAFAAQAGAAAAgIIgVkEIAJAAIARDfIARjfIAKAAIgYEFQgCAQgGAAgAgNiLQgGgGAAgIIAKAAQAAAEADADQADADADAAQADAAADgDQADgDAAgEIALAAQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape_44.setTransform(92.4,178.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#999999").s().p("AgHCLQgKAAAAgSIAAjyQAAgRANAAIAIAAQAOAAAAARIAADyQAAASgKAAgAgHh5IAADuQgBANAHgBIADAAQAGABABgNIAAjuQAAgIgFAAIgIAAQgDAAAAAIg");
	this.shape_45.setTransform(83.2,180.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB3QAAALgEACQgFADgGAAIgLAAIAACGgAgIgDIALAAQAGAAAAgJIAAhxQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_46.setTransform(74.8,180.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_47.setTransform(65.6,180.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#999999").s().p("AARCYIAAgaIghAAIAAAaIgJAAIAAgjIAFAAQAGAAAAgNIAAj/IAjAAIAAEMIAFAAIAAAjgAgFBtIAAAIIARAAIAAkCIgRAAg");
	this.shape_48.setTransform(55.5,181.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAANAGgBIAFAAQAGABAAgNIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGAAAAgJIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABuQAAALgGAAIADABQADABAAAJIAABuQAAASgJAAg");
	this.shape_49.setTransform(46.4,180.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#999999").s().p("AgQCLIAAgKIAFAAQAGABAAgJIgVkDIAJAAIARDeIARjeIAKAAIgYEFQgCAQgGAAg");
	this.shape_50.setTransform(26.5,180.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#999999").s().p("AARCLIAAiXIgMCXIgIAAIgOiXIAACXIgJAAIAAkVIAJAAIARDgIARjgIAKAAIAAEVg");
	this.shape_51.setTransform(16.4,180.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_52.setTransform(6.3,180.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#999999").s().p("AgfCLIAAkVIAJAAIAAELIATAAIAAkLIAHAAIAAELIATAAIAAkLIAJAAIAAEVg");
	this.shape_53.setTransform(-4.3,180.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAlIARAAIgJh5g");
	this.shape_54.setTransform(-15,180.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB3QAAALgGAAIADABQADABAAAJIAAB3QAAAJgEAAgAgICBIAOAAQADAAAAgGIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGAAAAgJIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_55.setTransform(-24.2,180.2);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#999999").s().p("AgRCLIAAkVIAJAAIAACHIALAAQAGAAAFADQAEADAAAKIAAB1QAAAJgGAAgAgICBIAPAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAAhvQAAgKgGAAIgLAAg");
	this.shape_56.setTransform(-43.2,180.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#999999").s().p("AAOCYIAAgaIgkAAIAAkVIAKAAIAAEMIAQAAIAAkMIAKAAIAAEMIAJAAIAAAjg");
	this.shape_57.setTransform(-52,181.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#999999").s().p("AgDCLIAAkVIAHAAIAAEVg");
	this.shape_58.setTransform(-59.4,180.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAANAGgBIAFAAQAGABAAgNIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGAAAAgJIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABuQAAALgGAAIADABQADABAAAJIAABuQAAASgJAAg");
	this.shape_59.setTransform(-66.4,180.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#999999").s().p("AARCYIAAgaIghAAIAAAaIgJAAIAAgjIAFAAQAGAAAAgNIAAj/IAjAAIAAEMIAFAAIAAAjgAgFBtIAAAIIARAAIAAkCIgRAAg");
	this.shape_60.setTransform(-75.5,181.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAjyQAAgRAOAAIAHAAQAOAAAAARIAADyQAAASgKAAgAgIh5IAADuQABANAFgBIAEAAQAHABgBgNIAAjuQAAgIgEAAIgHAAQgEAAgBAIg");
	this.shape_61.setTransform(-84.6,180.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#999999").s().p("AAJCLIgRiGIAACGIgJAAIAAkVIAJAAIAACHIARiHIAJAAIgSCKIASCLg");
	this.shape_62.setTransform(-93,180.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#999999").s().p("AgfCLIAAkVIAJAAIAAELIATAAIAAkLIAHAAIAAELIATAAIAAkLIAJAAIAAEVg");
	this.shape_63.setTransform(-102.7,180.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_64.setTransform(103.3,147.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgGAAIADAAQADACAAAIIAAB4QAAAJgEAAgAgICBIAOAAQADABAAgHIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_65.setTransform(94.1,147.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#999999").s().p("AgDCLIAAkVIAHAAIAAEVg");
	this.shape_66.setTransform(87.1,147.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#999999").s().p("AAJCLIAAkMIgRAAIAAEMIgJAAIAAkVIAjAAIAAEVg");
	this.shape_67.setTransform(80.2,147.5);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_68.setTransform(61.5,147.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_69.setTransform(53.5,147.5);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_70.setTransform(45.1,147.5);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_71.setTransform(35.9,147.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgGAAIADAAQADACAAAIIAAB4QAAAJgEAAgAgICBIAOAAQADABAAgHIAAhuQAAgIgGAAIgLAAgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_72.setTransform(26.6,147.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#999999").s().p("AAXCLIAAkVIAJAAIAAEVgAgfCLIAAkVIAJAAIAACHIANAAQAGABADACQAEADAAAKIAAB1QAAAJgEAAgAgWCBIARAAQAAAAABAAQAAAAAAgBQABAAAAgBQAAgBAAAAIAAhvQAAgKgGAAIgNAAg");
	this.shape_73.setTransform(16.9,147.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#999999").s().p("AAXCLIgTiGIAACGIgHAAIAAiGIgTCGIgJAAIAUiLIgUiKIAJAAIATCHIAAiHIAHAAIAACHIATiHIAJAAIgUCKIAUCLg");
	this.shape_74.setTransform(5.8,147.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#999999").s().p("AgQCaIAAgJIAFAAQAGAAAAgIIgVkEIAJAAIARDfIARjfIAKAAIgYEFQgCAQgGAAgAgNiLQgGgGAAgIIAKAAQAAAEADADQADADADAAQADAAADgDQADgDAAgEIALAAQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape_75.setTransform(-4.8,146);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_76.setTransform(-24.4,147.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_77.setTransform(-33.3,147.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#999999").s().p("AAJCLIAAiGIgRAAIAACGIgJAAIAAkVIAJAAIAACHIARAAIAAiHIAJAAIAAEVg");
	this.shape_78.setTransform(-42.6,147.5);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgEABQgFAEgGAAIgLAAIAACGgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_79.setTransform(-50.9,147.5);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#999999").s().p("AgOCLIAAkVIAdAAIAAAJIgUAAIAAB+IAUAAIAAAIIgUAAIAAB8IAUAAIAAAKg");
	this.shape_80.setTransform(-59,147.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#999999").s().p("AASCLIAAiXIgOCXIgIAAIgMiXIAACXIgKAAIAAkVIAKAAIAQDhIASjhIAJAAIAAEVg");
	this.shape_81.setTransform(-67.9,147.5);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#999999").s().p("AgICLQgJAAAAgSIAAhJIAJAAIAABFQAAAMAGAAIAFAAQAGAAAAgMIAAhoQAAgIgGAAIgPAAIAAgIIAPAAQAGABAAgKIAAhtQAAgIgEAAIgJAAQgEAAAAAIIAABJIgJAAIAAhJQAAgRANAAIAJAAQANAAAAARIAABvQAAAKgGAAIADAAQADACAAAIIAABvQAAASgJAAg");
	this.shape_82.setTransform(-77.1,147.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#999999").s().p("AASCLIgHhdIgTAAIgIBdIgKAAIAakVIAFAAIAWEVgAgHAkIARAAIgJh4g");
	this.shape_83.setTransform(-86.4,147.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#999999").s().p("AgRCLIAAkVIAdAAQAGAAAAAIIAAB4QAAAKgEABQgFAEgGAAIgLAAIAACGgAgIgDIALAAQAGABAAgKIAAhxQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgPAAg");
	this.shape_84.setTransform(-95.6,147.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#999999").s().p("AAJCLIAAkMIgRAAIAAEMIgJAAIAAkVIAjAAIAAEVg");
	this.shape_85.setTransform(-104,147.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// blk
	this.blk = new lib.blk();

	this.timeline.addTween(cjs.Tween.get(this.blk).wait(1));

	// btn
	this.btn = new lib.Symbol9copy();

	this.timeline.addTween(cjs.Tween.get(this.btn).wait(1));

	// ili
	this.ili = new lib.Symbol9();

	this.timeline.addTween(cjs.Tween.get(this.ili).wait(1));

	// gb
	this.gb = new lib.gb();
	this.gb.setTransform(-71,-23);

	this.timeline.addTween(cjs.Tween.get(this.gb).wait(1));

	// gb_t1
	this.gb_t1 = new lib.gb_t1();

	this.timeline.addTween(cjs.Tween.get(this.gb_t1).wait(1));

	// ira
	this.ira = new lib.ira();
	this.ira.setTransform(-71,-23);

	this.timeline.addTween(cjs.Tween.get(this.ira).wait(1));

	// ira_t1
	this.ira_t1 = new lib.ira_t1();

	this.timeline.addTween(cjs.Tween.get(this.ira_t1).wait(1));

	// bg1
	this.bg1 = new lib.bg_shine_1();
	this.bg1.setTransform(-71,-28);

	this.timeline.addTween(cjs.Tween.get(this.bg1).wait(1));

	// t2
	this.t2 = new lib.t2();
	this.t2.setTransform(0,-153.5);

	this.timeline.addTween(cjs.Tween.get(this.t2).wait(1));

	// pack
	this.pack = new lib.Symbol15();
	this.pack.setTransform(-2,3.5,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.pack).wait(1));

	// bg_pattern
	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AyufPMAAAg+dMAldAAAMAAAA+dg");

	this.timeline.addTween(cjs.Tween.get(this.shape_86).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-386.2,-621.5,887.9,1002.5);


// stage content:
(lib.km1_240x400 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyufQMAAAg+fMAldAAAMAAAA+fg");
	mask.setTransform(120,200);

	// movie
	this.rolik = new lib.content();
	this.rolik.setTransform(120,200);

	this.rolik.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.rolik).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(120,200,240,400);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;